services:
  api:
    container_name: flask-jwt-api
    image: docker.io/macripco/flask-jwt-api-starter-api:latest
    ports:
      - "5001:5000"          # host:container
    env_file: .env
    volumes:
      - dbdata:/app/instance # datos locales de Flask
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  dbdata:
